export default {
  id: "a820ad09876754cae2b1d44da01d0d9f8a83749d",
  uploadTime: "2020-03-20T11:16:11.196Z",
  uploadedBy: "pa",
  lastModified: "2020-03-20T11:16:11.196Z",
  identifiers: {},
  uploadInfo: {
    filename: "ANIMALS_Elephant_11138514.jpg",
  },
  source: {
    file: "http://media-service-imagebucket.grid.local/a/8/2/0/a/d/a820ad09876754cae2b1d44da01d0d9f8a83749d",
    size: 0,
    mimeType: "image/jpeg",
    dimensions: {
      width: 1914,
      height: 1314,
    },
    secureUrl: "https://media-service-imagebucket.grid.local/a/8/2/0/a/d/a820ad09876754cae2b1d44da01d0d9f8a83749d",
  },
  thumbnail: {
    file: "http://media-service-thumbbucket.grid.local/a/8/2/0/a/d/a820ad09876754cae2b1d44da01d0d9f8a83749d",
    size: 14743,
    mimeType: "image/jpeg",
    dimensions: {
      width: 256,
      height: 176,
    },
    secureUrl: "https://media-service-thumbbucket.grid.local/a/8/2/0/a/d/a820ad09876754cae2b1d44da01d0d9f8a83749d",
  },
  fileMetadata: {},
  metadata: {
    dateTaken: "2020-03-20T10:15:02.170Z",
    description:
      "Riva Hi Way, a baby Asian elephant calf born last month at Chester Zoo, makes her public debut alongside her mother 15-year-old Sundara Hi Way. PA Photo. Picture date: Friday March 20, 2020. The calf was born after a 22 month pregnancy. Asian elephants are listed as endangered by the International Union for the Conservation of Nature (IUCN) and the species is highly threatened in the wild by habitat loss, poaching, human-wildlife conflict and a deadly herpes virus called Elephant Endotheliotropic Herpesvirus.  Photo credit should read: Peter Byrne/PA Wire",
    credit: "PA",
    byline: "Peter Byrne",
    title: "Baby elephant at Chester zoo",
    suppliersReference: "ANIMALS_Elephant_11138514.JPG",
    source: "PA",
    city: "Chester",
    country: "United Kingdom",
    subjects: ["news"],
  },
  originalMetadata: {
    dateTaken: "2020-03-20T10:15:02.170Z",
    description:
      "Riva Hi Way, a baby Asian elephant calf born last month at Chester Zoo, makes her public debut alongside her mother 15-year-old Sundara Hi Way. PA Photo. Picture date: Friday March 20, 2020. The calf was born after a 22 month pregnancy. Asian elephants are listed as endangered by the International Union for the Conservation of Nature (IUCN) and the species is highly threatened in the wild by habitat loss, poaching, human-wildlife conflict and a deadly herpes virus called Elephant Endotheliotropic Herpesvirus.  Photo credit should read: Peter Byrne/PA Wire",
    credit: "PA",
    byline: "Peter Byrne",
    title: "Baby elephant at Chester zoo",
    suppliersReference: "ANIMALS_Elephant_11138514.JPG",
    source: "PA",
    city: "Chester",
    country: "United Kingdom",
    subjects: ["news"],
  },
  usageRights: {
    category: "agency",
    supplier: "PA",
  },
  originalUsageRights: {
    category: "agency",
    supplier: "PA",
  },
  exports: [],
  usages: {},
  leases: {},
  collections: [],
  syndicationRights: null,
  userMetadata: {},
  valid: true,
  invalidReasons: {},
  cost: "free",
  persisted: {
    value: false,
    reasons: [],
  },
  syndicationStatus: "unsuitable",
};
